server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/keev-loop/codebuffer-mss/config
          clone-on-start: true
    
